export const addConstants = {

    EDIT_CONFIG_PRICE_REQUEST: 'EDIT_CONFIG_PRICE_REQUEST',
    EDIT_CONFIG_PRICE_SUCCESS: 'EDIT_CONFIG_PRICE_SUCCESS',
    EDIT_CONFIG_PRICE_FAILURE: 'EDIT_CONFIG_PRICE_FAILURE',


}