export const deliveryChargesConstants = {

    GET_DELIVERY_CHARGES_REQUEST: 'GET_DELIVERY_CHARGES_REQUEST',
    GET_DELIVERY_CHARGES_SUCCESS: 'GET_DELIVERY_CHARGES_SUCCESS',
    GET_DELIVERY_CHARGES_FAILURE: 'GET_DELIVERY_CHARGES_FAILURE',

    ADD_DELIVERY_CHARGES_REQUEST: 'ADD_DELIVERY_CHARGES_REQUEST',
    ADD_DELIVERY_CHARGES_SUCCESS: 'ADD_DELIVERY_CHARGES_SUCCESS',
    ADD_DELIVERY_CHARGES_FAILURE: 'ADD_DELIVERY_CHARGES_FAILURE'

}



