export const deliveryChargesConstants = {

    GET_DELIVERY_CHARGES_REQUEST: 'GET_DELIVERY_CHARGES_REQUEST',
    GET_DELIVERY_CHARGES_SUCCESS: 'GET_DELIVERY_CHARGES_SUCCESS',
    GET_DELIVERY_CHARGES_FAILURE: 'GET_DELIVERY_CHARGES_FAILURE'

}