export const employeeConstants = {
    
    ADD_EMPLOYEE_REQUEST: 'ADD_EMPLOYEE_REQUEST',
    ADD_EMPLOYEE_SUCCESS: 'ADD_EMPLOYEE_SUCCESS',
    ADD_EMPLOYEE_FAILURE: 'ADD_EMPLOYEE_FAILURE',

    GET_EMPLOYEES_REQUEST: "GET_EMPLOYEES_REQUEST",
    GET_EMPLOYEES_SUCCESS: "GET_EMPLOYEES_SUCCESS",
    GET_EMPLOYEES_FAILURE: "GET_EMPLOYEES_FAILURE"
    
};
