export const getConstants = {

    GET_CONFIG_PRICE_REQUEST: 'GET_CONFIG_PRICE_REQUEST',
    GET_CONFIG_PRICE_SUCCESS: 'GET_CONFIG_PRICE_SUCCESS',
    GET_CONFIG_PRICE_FAILURE: 'GET_CONFIG_PRICE_FAILURE',


}