export const orderConstants = {
    
    ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
    ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
    ADD_ORDER_FAILURE: 'ADD_ORDER_FAILURE',

    GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST',
    GET_ORDERS_SUCCESS: 'GET_ORDERS_SUCCESS',
    GET_ORDERS_FAILURE: 'GET_ORDERS_FAILURE',
    
    EDIT_ORDER_STATUS_REQUEST: 'EDIT_ORDER_STATUS_REQUEST',
    EDIT_ORDER_STATUS_SUCCESS: 'EDIT_ORDER_STATUS_SUCCESS',
    EDIT_ORDER_STATUS_FAILURE: 'EDIT_ORDER_STATUS_FAILURE',

    GET_ORDER_SMS_REQUEST: 'GET_ORDER_SMS_REQUEST',
    GET_ORDER_SMS_SUCCESS: 'GET_ORDER_SMS_SUCCESS',
    GET_ORDER_SMS_FAILURE: 'GET_ORDER_SMS_FAILURE',

    EDIT_ORDER_SMS_REQUEST: 'EDIT_ORDER_SMS_REQUEST',
    EDIT_ORDER_SMS_SUCCESS: 'EDIT_ORDER_SMS_SUCCESS',
    EDIT_ORDER_SMS_FAILURE: 'EDIT_ORDER_SMS_FAILURE',

    ADD_ORDER_FILTER: 'ADD_ORDER_FILTER'
}