export const settingsConstants = {

    GET_ORDER_SETTINGS_REQUEST: 'GET_ORDER_SETTINGS_REQUEST',
    GET_ORDER_SETTINGS_SUCCESS: 'GET_ORDER_SETTINGS_SUCCESS',
    GET_ORDER_SETTINGS_FAILURE: 'GET_ORDER_SETTINGS_FAILURE',

    EDIT_ORDER_SETTINGS_REQUEST: 'EDIT_ORDER_SETTINGS_REQUEST',
    EDIT_ORDER_SETTINGS_SUCCESS: 'EDIT_ORDER_SETTINGS_SUCCESS',
    EDIT_ORDER_SETTINGS_FAILURE: 'EDIT_ORDER_SETTINGS_FAILURE',

    GET_PRICING_REQUEST: 'GET_PRICING_REQUEST',
    GET_PRICING_SUCCESS: 'GET_PRICING_SUCCESS',
    GET_PRICING_FAILURE: 'GET_PRICING_FAILURE',

}