export const settingsConstants = {

    GET_ORDER_SETTINGS_REQUEST: 'GET_ORDER_SETTINGS_REQUEST',
    GET_ORDER_SETTINGS_SUCCESS: 'GET_ORDER_SETTINGS_SUCCESS',
    GET_ORDER_SETTINGS_FAILURE: 'GET_ORDER_SETTINGS_FAILURE',

    EDIT_ORDER_SMS_REQUEST: 'EDIT_ORDER_SMS_REQUEST',
    EDIT_ORDER_SMS_SUCCESS: 'EDIT_ORDER_SMS_SUCCESS',
    EDIT_ORDER_SMS_FAILURE: 'EDIT_ORDER_SMS_FAILURE',
    
    EDIT_ORDER_SMS: 'EDIT_ORDER_SMS',
}