export const stationConstants = {

    GET_STATIONS_REQUEST: 'GET_STATIONS_REQUEST',
    GET_STATIONS_SUCCESS: 'GET_STATIONS_SUCCESS',
    GET_STATIONS_FAILURE: 'GET_STATIONS_FAILURE',

    ADD_STATION_REQUEST: 'ADD_STATION_REQUEST',
    ADD_STATION_SUCCESS: 'ADD_STATION_SUCCESS',
    ADD_STATION_FAILURE: 'ADD_STATION_FAILURE',

    EDIT_STATION_REQUEST: 'EDIT_STATION_REQUEST',
    EDIT_STATION_SUCCESS: 'EDIT_STATION_SUCCESS',
    EDIT_STATION_FAILURE: 'EDIT_STATION_FAILURE'

}