export const userConstants = {
    
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    
    VERIFICATION_CODE_REQUEST: 'VERIFICATION_CODE_REQUEST',
    VERIFICATION_CODE_SUCCESS: 'VERIFICATION_CODE_SUCCESS',
    VERIFICATION_CODE_FAILURE: 'VERIFICATION_CODE_FAILURE', 
    
    USER_INFO_REQUEST: 'USER_INFO_REQUEST',
    USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
    USER_INFO_FAILURE: 'USER_INFO_FAILURE'
    
};
